# The template for this tool description is generated by APE (https://github.com/workflomics/ape).
cwlVersion: v1.2
class: CommandLineTool
baseCommand: http://edamontology.org/comet[tool]
label: Comet
requirements:
  ShellCommandRequirement: {}
  InitialWorkDirRequirement:
    listing:
      - $(inputs.Comet_-_0)
      - $(inputs.Comet_-_1)
  DockerRequirement:
    dockerPull: fix-this-path/Comet

$namespaces:
  edam: http://edamontology.org/

intent:
  - http://edamontology.org/operation_3646

inputs:
  Comet_in_0:
    type: File
    format: "http://edamontology.org/format_3244"  # mzML
    doc: The I/O is annotated with multiple formats in bio.tools. We specified here the first one. To implement other combinations you would have to create more CWL files. Please check the instructions on how to handle such cases: https://workflomics.readthedocs.io/en/latest/domain-expert-guide/domain-development.html
    edam:data_0006: "http://edamontology.org/data_0943"  # Mass spectrum

  Comet_in_1:
    type: File
    format: "http://edamontology.org/format_1929"  # FASTA

    edam:data_0006: "http://edamontology.org/data_2976"  # Protein sequence

outputs:
  Comet_out_0:
    type: File
    format: "http://edamontology.org/format_3247"  # mzIdentML
    doc: The I/O is annotated with multiple formats in bio.tools. We specified here the first one. To implement other combinations you would have to create more CWL files. Please check the instructions on how to handle such cases: https://workflomics.readthedocs.io/en/latest/domain-expert-guide/domain-development.html
    edam:data_0006: "http://edamontology.org/data_0945"  # Peptide identification

